name: flutter_base_app
description: A base project on Flutter.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.2
  bloc: 0.15.0
  flutter_bloc: 0.21.0
  meta: 1.1.7
  equatable: 0.5.1
  http: 0.12.0+2
  json_annotation: 3.0.0
  cached_network_image: 1.1.1
  package_info: 0.4.0+6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.7.0
  json_serializable: 3.2.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/africa/africa.png
    - assets/images/africa/2x/africa.png
    - assets/images/africa/3x/africa.png
    - assets/images/america/america.png
    - assets/images/america/2x/america.png
    - assets/images/america/3x/america.png
    - assets/images/asia/asia.png
    - assets/images/asia/2x/asia.png
    - assets/images/asia/3x/asia.png
    - assets/images/back_arrow/back_arrow.png
    - assets/images/back_arrow/2x/back_arrow.png
    - assets/images/back_arrow/3x/back_arrow.png
    - assets/images/europe/europe.png
    - assets/images/europe/2x/europe.png
    - assets/images/europe/3x/europe.png
    - assets/images/flag/flag.png
    - assets/images/flag/2x/flag.png
    - assets/images/flag/3x/flag.png
    - assets/images/logo_white/logo_white.png
    - assets/images/logo_white/2x/logo_white.png
    - assets/images/logo_white/3x/logo_white.png
    - assets/images/oceania/oceania.png
    - assets/images/oceania/2x/oceania.png
    - assets/images/oceania/3x/oceania.png
    - assets/images/region/region.png
    - assets/images/region/2x/region.png
    - assets/images/region/3x/region.png
    - assets/languages/en.json
    - assets/languages/de.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.otf
        - asset: assets/fonts/Quicksand-Regular.otf
